### PR TITLE
Switch default interpreter to python3

### PR DESCRIPTION
**Pull request by paulbovbel**
I'm torn about the best way to do this, but willing to collect thoughts here. A hard cutover and then picking up the pieces probably isn't the worst way.

@garyservin is closing on a focal/noetic/python3 bundle, and we will need to stop using python2 virtualenvs as well.

### CODE REVIEW

**Review by garyservin — APPROVED** [review]

**Review by MJohnson459 — APPROVED** [review]
I agree, this seems like the best approach. I wonder how many packages were actually using virtualenv for python2 anyway. I guess we will find out.

**Comment by paulbovbel** [comment]
This branch is now in the focal feature bundle, so this will be an interesting experiment

**Comment by abencz** [comment]
locus_behavior_engine will definitely break: https://github.com/locusrobotics/locus_behavior_engine/blob/fbcad55c304d057a7945e757fe02013e62bf36cb/locus_behavior_engine/CMakeLists.txt#L6

**Review by abencz — APPROVED** [review]

**Comment by paulbovbel** [comment]
> locus_behavior_engine will definitely break:

You're right, I think maybe a different tack is in order - update all default usage to `python2`, make a list of packages to fix for 21, then change the default.

**Review by ablakey — APPROVED** [review]

**Pull request merged**
